name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.0
        with:
          cmake-version: "3.16.x"
      - name: Cmake Makefiles
        run: cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: Run make
        run: cd ./sbgECom/projects/unix; make
      - name: "Upload Binary"
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: ./sbgECom/bin

      - name: "HOTFIRE_TEST: Cmake Makefiles"
        run: export USE_SBG=1; cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: "USE_SBG: Run make"
        run: export USE_SBG=1; cd ./sbgECom/projects/unix; make

      - name: "SKIP_INIT: Cmake Makefiles"
        run: export SKIP_INIT=1; cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: "SKIP_INIT: Run make"
        run: export SKIP_INIT=1; cd ./sbgECom/projects/unix; make
        
      - name: "HOTFIRE_TEST and SKIP_INIT: Cmake Makefiles"
        run: export HOTFIRE_TEST=1; export SKIP_INIT=1; cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: "HOTFIRE_TEST and SKIP_INIT: Run make"
        run: export HOTFIRE_TEST=1; export SKIP_INIT=1; cd ./sbgECom/projects/unix; make

      - name: "TESTING: Cmake Makefiles"
        run: export TESTING=1; cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: "TESTING: Run make"
        run: export TESTING=1; cd ./sbgECom/projects/unix; make

      - name: "HOTFIRE_TEST and TESTING: Cmake Makefiles"
        run: export HOTFIRE_TEST=1; export TESTING=1; cd ./sbgECom/projects/unix; cmake -G 'Unix Makefiles'
      - name: "HOTFIRE_TEST and TESTING: Run make"
        run: export HOTFIRE_TEST=1; export TESTING=1; cd ./sbgECom/projects/unix; make
