name: Build

on: [push, pull_request]

jobs:
  build_default:
    name: Build Default
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Cmake Makefiles
        run: cmake -B ./build -G 'Unix Makefiles'
      - name: Run make
        run: cmake --build ./build --target MainLoop
      - name: "Upload Binary"
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: ./build/MainLoop

  build_environments:
    name: Build Environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "HOTFIRE_TEST"
            append: export HOTFIRE_TEST=1;
          - name: "USE_SBG"
            append: export USE_SBG=1;
          - name: "SKIP_INIT"
            append: export SKIP_INIT=1;
          - name: "HOTFIRE_TEST and SKIP_INIT"
            append: export HOTFIRE_TEST=1; export SKIP_INIT=1;
          - name: "TESTING"
            append: export TESTING=1;
          - name: "HOTFIRE_TEST and TESTING"
            append: export HOTFIRE_TEST=1; export TESTING=1;

    steps:
      # Initialization
      - uses: actions/checkout@v1
        with:
          submodules: true
      # Build the project
      - name: "${{ matrix.name }}: Cmake Makefiles"
        run: ${{ matrix.append }} cmake -B ./build -G 'Unix Makefiles'
      - name: "${{ matrix.name }}: Run make"
        run: ${{ matrix.append }} cmake --build ./build --target MainLoop
