name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Default"
            append:
          - name: "HOTFIRE_TEST"
            append: export HOTFIRE_TEST=1;
          - name: "USE_SBG"
            append: export USE_SBG=1;
          - name: "SKIP_INIT"
            append: export SKIP_INIT=1;
          - name: "HOTFIRE_TEST and SKIP_INIT"
            append: export HOTFIRE_TEST=1; export SKIP_INIT=1;
          - name: "TESTING"
            append: export TESTING=1;
          - name: "HOTFIRE_TEST and TESTING"
            append: export HOTFIRE_TEST=1; export TESTING=1;

    steps:
      # Initialization
      - uses: actions/checkout@v1
        with:
          submodules: true
      # Build the project
      - name: "${{ matrix.name }}: Cmake Makefiles"
        run: ${{ matrix.append }} cmake -B ./build -G 'Unix Makefiles'
      - name: "${{ matrix.name }}: Run make"
        run: ${{ matrix.append }} cmake --build ./build --target MainLoop
