name: Build

on: [push, pull_request]

jobs:
  build:
    name: End-to-end
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: "3.16.x"
      - name: Run octoberSky Test
        run: cd ./tests/octoberSky/; ./run_test.sh
