name: Unit Testing

on: [push, pull_request]

jobs:
  unit_testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Cmake Makefiles
        run: cmake -B ./build -G 'Unix Makefiles'
      - name: Run make
        run: cmake --build ./build --target tests
      - name: Run Unit Tests
        run: ./build/tests
